language: python
python:
- '3.6'
install:
- pip install numpy
- pip install pandas
- pip install plotly
script:
- python python/BlueRidgeRelay2017.py
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git config --global push.default simple
deploy:
  provider: script
  script: ".travis/rebuild-ragnar.sh"
  github_token: $GITHUB_TOKEN # Set in travis-ci.org project settings
  skip_cleanup: true
  on:
    branch: master
