language: python

python:
  - "3.6"

install:
  - pip install numpy
  - pip install pandas
  - pip install plotly

script:
  - python python/AtlantaRagnar2017.py

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - .travis/rebuild-ragnar.sh .
