language: python

python:
  - "3.6"

install:
  - pip install numpy
  - pip install pandas
  - pip install plotly

script:
  - python python/AtlantaRagnar2017.py

deploy:
  provider: script
  api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  skip_cleanup: true
  script: .travis/rebuild-ragnar.sh pwd
  on:
    branch: master
